name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_MODAL_LABS_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_MODAL_LABS_TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Setup Python 3.10
        with:
          python-version: '3.10' 

      - name: Install Modal client package and jupytext
        run: pip3 install modal-client jupytext pydantic

      - name: Run deployment script
        run: |
            modal deploy app.py
